// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnGBicdszdrxkO2bvv8uuEPxQTn1whv0I',
    appId: '1:503224830946:web:12f183a983fb46571d87bb',
    messagingSenderId: '503224830946',
    projectId: 'movies-db1db',
    authDomain: 'movies-db1db.firebaseapp.com',
    storageBucket: 'movies-db1db.firebasestorage.app',
    measurementId: 'G-2CRDZSHHMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUJO0Hh5Oqp7qwKNrNlNND8MVeY2HwTNw',
    appId: '1:503224830946:android:b143add4fe919add1d87bb',
    messagingSenderId: '503224830946',
    projectId: 'movies-db1db',
    storageBucket: 'movies-db1db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPsTF-qqzZoN5-XvOR703w3Av_UfBnFHM',
    appId: '1:503224830946:ios:12a3e6705d23edee1d87bb',
    messagingSenderId: '503224830946',
    projectId: 'movies-db1db',
    storageBucket: 'movies-db1db.firebasestorage.app',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPsTF-qqzZoN5-XvOR703w3Av_UfBnFHM',
    appId: '1:503224830946:ios:12a3e6705d23edee1d87bb',
    messagingSenderId: '503224830946',
    projectId: 'movies-db1db',
    storageBucket: 'movies-db1db.firebasestorage.app',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnGBicdszdrxkO2bvv8uuEPxQTn1whv0I',
    appId: '1:503224830946:web:dfbaed2127104db71d87bb',
    messagingSenderId: '503224830946',
    projectId: 'movies-db1db',
    authDomain: 'movies-db1db.firebaseapp.com',
    storageBucket: 'movies-db1db.firebasestorage.app',
    measurementId: 'G-8E9DSRTPEE',
  );
}
